- name: Install DNF packages
  dnf:
    name:
      - mc
      - sublime-text
      - curl
      - gnupg2
      - yt-dlp
      - gimp
      - okular
      - gparted
      - transmission-gtk
      - vlc
      - ffmpeg  # This will now work with the 'allowerasing' flag below
      - gpick
      - tlp
      - calibre
      - nss
      - pandoc
      - rEFInd  # Fixed case-sensitivity
      - hunspell-es
      - ImageMagick
      - unrar
      - net-tools
    state: present
    allowerasing: yes  # This allows dnf to swap ffmpeg-free for the full version
