- name: Create mount points
  file:
    path: "/mnt/{{ item }}"
    state: directory
  with_items: [pop, shared_data, windows]

- name: Configure FSTAB
  lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
  with_items:
    - 'UUID=700FF4BE379CCE65  /mnt/shared_data  ntfs-3g  defaults,uid=1000,gid=1000  0  2'
    - 'UUID=c445160d-43ba-4301-b7cd-7d0df6367a4a  /mnt/pop  ext4  defaults  0  2'
    - 'UUID=4A96B7C096B7AB39  /mnt/windows  ntfs-3g  defaults,uid=1000,gid=1000  0  0'
